const Header = (props) => {
  return <h1>{props.course}</h1>
}

const Content = (props) => {
    return props.parts.map((part) => {
      return <p key={part.name}>{part.name} {part.exercises}</p> 
    })
}
//rendering multiple elements in a component requires a key so that React doesn't have to re-render the
//entire component if it needs to rerender a single element generated by this component

const Total = (props) => {
  let total = 0
  for (let i = 0; i < props.parts.length; i++) {
    total += props.parts[i].exercises
  }
  return (<p>Number of exercises {total}</p>)
}

const App = () => {
  const course = 'Half Stack application development'
  const parts = [{name:'Fundamentals of React', exercises: 10},
                 {name: 'Using props to pass data', exercises: 7},
                 {name: 'State of a component', exercises: 14}]

  return (
    <>
      <Header course={course} />
      <Content parts={parts} />
      <Total parts={parts} />
    </>
  )
}

export default App